=== bobmwangih/Contract-First-WebService/target/classes/testXsds/students.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/students"
	xmlns:tns="http://www.example.org/students"
	elementFormDefault="qualified">

	<element name="studentsList" type="tns:studentsType"></element>

	<complexType name="studentsType">
		<sequence>
			<element name="student" type="tns:studentType" maxOccurs="3"
				minOccurs="1"></element>
		</sequence>
	</complexType>

	<complexType name="studentType">
		<sequence>
			<element name="employeeId" type="tns:empId"></element>
			<element name="firstName" type="string"></element>
			<element name="lastName" type="string"></element>
			<element name="email" type="string"></element>
		</sequence>
		<attribute name="Sid" type="ID" use="required"></attribute>
	</complexType>

	<simpleType name="empId">
		<restriction base="integer">
			<minInclusive value="5"></minInclusive>
			<maxInclusive value="10"></maxInclusive>
		</restriction>
	</simpleType>
</schema>

=== bobmwangih/Contract-First-WebService/src/main/resources/testXsds/students.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:studentsList
	xmlns:tns="http://www.example.org/students"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/students students.xsd ">

	<tns:student Sid="idvalue0">
		<tns:employeeId>5</tns:employeeId>
		<tns:firstName>spider</tns:firstName>
		<tns:lastName>man</tns:lastName>
		<tns:email>man@spider.com</tns:email>
	</tns:student>

	<tns:student Sid="idvalue1">
		<tns:employeeId>6</tns:employeeId>
		<tns:firstName>aqua</tns:firstName>
		<tns:lastName>man</tns:lastName>
		<tns:email>man@aqua.com</tns:email>
	</tns:student>

	<tns:student Sid="idvalue2">
		<tns:employeeId>7</tns:employeeId>
		<tns:firstName>country</tns:firstName>
		<tns:lastName>man</tns:lastName>
		<tns:email>man@country.com</tns:email>
	</tns:student>
</tns:studentsList>
